- name: Create kiskadee user
  user:
    name: kiskadee
    group: wheel
    shell: /bin/bash

# TODO: do not turn selinux off. Add rules instead
- name: Turn off selinux
  command: setenforce 0
  ignore_errors: yes

- name: Setup kiskadee repository
  copy: src=davidcarlos-kiskadee-fedora-27.repo dest=/etc/yum.repos.d/kiskadee.repo

- name: Install kiskadee
  dnf: name={{ item }} state=installed
  with_items:
    - kiskadee

# We now build the docker images
- name: Clone kiskadee repository
  git:
    repo: https://pagure.io/kiskadee.git
    dest: /tmp/kiskadee
    force: yes

- name: build docker images
  make:
    chdir: /tmp/kiskadee
    target: analyzers

#- name: Enable kiskadee
  #service:
    #name: kiskadee
    #enabled: yes

#- name: Start kiskadee
  #service:
    #name: kiskadee
    #state: started
