- name: Create kiskadee group
  group:
    name: kiskadee
    state: present

- name: Create kiskadee user
  user:
    name: kiskadee
    groups: kiskadee, wheel
    append: yes
    shell: /bin/bash

# TODO: do not turn selinux off. Add rules instead
- name: Turn off selinux
  command: setenforce 0
  ignore_errors: yes

- name: Setup kiskadee repository
  copy: src=davidcarlos-kiskadee-fedora-27.repo dest=/etc/yum.repos.d/kiskadee.repo

- name: Install kiskadee
  dnf: name={{ item }} state=latest
  with_items:
    - kiskadee

- name: Install kiskadee configuration file
  template:
    src: kiskadee.conf
    dest: /etc/kiskadee.conf
    force: yes
    mode: 0644

- name: Install fedmsg configuration file
  copy:
    src: endpoints.py
    dest: /etc/fedmsg.d/endpoints.py
    force: yes
    mode: 0644

# We now build the docker images
- name: Clone kiskadee repository
  git:
    repo: https://pagure.io/kiskadee.git
    dest: /tmp/kiskadee
    force: yes

- name: build docker images
  make:
    chdir: /tmp/kiskadee
    target: analyzers

- name: Enable fedmsg-hub
  service:
    name: fedmsg-hub-3
    enabled: yes

- name: Start fedmsg-hub
  service:
    name: fedmsg-hub-3
    state: started

- name: Enable kiskadee
  service:
    name: kiskadee
    enabled: yes

- name: Start kiskadee
  service:
    name: kiskadee
    state: started

- name: Enable kiskadee_api
  service:
    name: kiskadee_api
    enabled: yes

- name: Start kiskadee_api
  service:
    name: kiskadee_api
    state: started
