- name: Install kiskadee
  command: pip3 install -e .
  args:
    chdir: /home/vagrant/kiskadee

- name: Install fedmsg consumers
  pip:
     executable: pip3
     name: "fedmsg[consumers]"

- name: make analyzers
  make:
    chdir: /home/vagrant/kiskadee
    target: analyzers

- name: Turn off selinux
  command: setenforce 0
  ignore_errors: yes
