- name: Turn off selinux
  command: setenforce 0
  ignore_errors: yes

- name: Install kiskadee
  command: pip3 install -e .
  args:
    chdir: /home/vagrant/kiskadee

# Setuptools not installs test dependencies declared on setup.py, he just
# download it as a .egg packages (.egg packages can be installed with easy_install)
- name: Install kiskadee test dependencies
  command: pip3 install -r test_requirements.txt
  args:
    chdir: /home/vagrant/kiskadee

- name: Install fedmsg consumers
  pip:
     executable: pip3
     name: "fedmsg[consumers]"

- name: make analyzers
  make:
    chdir: /home/vagrant/kiskadee
    target: analyzers

- name: migrate database
  command: alembic upgrade head
  args:
    chdir: /home/vagrant/kiskadee
