- name: Instal virtualenvwrapper package
  pip:
    name: virtualenvwrapper
    executable: pip3

# TODO: do this only once
- name: source virtualenvwrapper
  shell: echo source /usr/bin/virtualenvwrapper.sh >> /home/vagrant/.bashrc

# TODO: do this only once
- name: Export workon env
  shell: echo export WORKON_HOME=/home/vagrant/Envs >> /home/vagrant/.bashrc

  # TODO: do this only once
- name: Export python version
  shell: echo export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3" >> /home/vagrant/.bashrc

- name: Change virtualenv path permitions
  file:
    path: /home/vagrant/Envs
    owner: vagrant
    state: directory
    mode: 0755
