- name: Instal virtualenvwrapper package
  pip:
    name: virtualenvwrapper
    executable: pip3

# TODO: do this only once
- name: source virtualenvwrapper
  shell: echo source /usr/bin/virtualenvwrapper.sh >> /home/kiskadee/.bashrc

# TODO: do this only once
- name: Export workon env
  shell: echo export WORKON_HOME=/home/kiskadee/Envs >> /home/kiskadee/.bashrc

  # TODO: do this only once
- name: Export python version
  shell: echo export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3" >> /home/kiskadee/.bashrc

- name: Change virtualenv path permitions
  file:
    path: /home/kiskadee/Envs
    owner: kiskadee
    state: directory
    mode: 0755

- name: Create kiskadee virtualenv
  environment:
    WORKON_HOME: /home/kiskadee/Envs
    VIRTUALENVWRAPPER_PYTHON: "/usr/bin/python3"
  shell: source /usr/bin/virtualenvwrapper.sh && mkvirtualenv --python=/usr/bin/python3 kiskadee
  chdir: /home/kiskadee/kiskadee
  become: true
  become_user: kiskadee

- name: Install kiskadee dependencies
  environment:
    WORKON_HOME: /home/kiskadee/Envs
    VIRTUALENVWRAPPER_PYTHON: "/usr/bin/python3"
  shell: source /usr/bin/virtualenvwrapper.sh && workon kiskadee && pip install -e . && pip install "fedmsg[consumers]"
  become: true
  become_user: kiskadee
  args:
    chdir: /home/kiskadee/kiskadee/

- name: build docker images
  make:
    chdir: /home/kiskadee/kiskadee
    target: analyzers
  become: true
  become_user: kiskadee

