- name: install fedora dependencies
  dnf: name={{ item }} state=installed
  with_items:
    - openssl-devel
    - python2-devel
    - python3-devel
    - gcc
    - redhat-rpm-config
    - python3-pip
    - dnf-plugins-core
    - git
    - postgresql-server
    - postgresql-contrib
    - libselinux-python
    - devscripts
  ignore_errors: yes
