- name: Install docker engine
  dnf: name=docker

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Start docker service
  service:
    name: docker
    state: started

- name: Change docker socket permitions
  file:
    path: /var/run/docker.sock
    mode: 0777

